### ISSUE TITLE
Users with comment/view permissions can not interact

### ISSUE THREAD

**Issue by josephwegner** [quip/quip-apps#63]
It seems that when a user has comment or view permissions on a document, their interactions do not propagate into the live app. Clicks, hovers, etc. are not even registered.

Is there a way to make it so these interactions are passed into the app, and I can do my own access model in React?

**Comment by jesseditson** [comment]
Not currently (because live apps are treated as document data) - but I do understand the use case of wanting to build read-only UI that responds to user interactions.
There's a bit of subtlety here though given that we wouldn't be able to delegate the entire permissions model to the app, so I'll log this as a feature request for us to consider in upcoming releases.

**Comment by josephwegner** [comment]
Note that I was able to fix this by applying `pointer-events: all` on the elements that I wanted to enable interaction.

I expect this breaks if I use it on an editable component, but in my particular scenario I am just enabling navigation components.

**Comment by jdoconnor** [comment]
If that's the case, should we consider this close-able? Also, Hi @josephwegner - long time, no see.

**Comment by josephwegner** [comment]
Hey there :)

Closing works for me. The solution at the time found hacky, but if this is the intended route then nothing to see here. Maybe something to add to the docs, if other developers have similar desires.
